### ISSUE TITLE
Cannot find module 'simplesmtp'

### ISSUE THREAD

**Issue by michielbdejong** [sockethub/sockethub#104]
after following the install instructions (with the necessary workarounds to get it to work on Debian), i get this:

```
message: { [Error: Cannot find module 'simplesmtp'] code: 'MODULE_NOT_FOUND' },
  stack: 'Error: Cannot find module \'simplesmtp\'\n
```

**Comment by LaNa215** [comment]
i m using sublime text editor ,windows...i got the same error...i just installed nodemailer globally...
try this :  npm install nodemailer..

**Comment by LaNa215** [comment]
install nodemailer...try this: npm install nodemailer

**Comment by skddc** [comment]
@LaNa215 How does nodemailer relate to this issue?

**Comment by skddc** [comment]
@silverbucket Shouldn't `nodemailer` be part of the `package.json` dependencies then?

**Comment by silverbucket** [comment]
This is no longer applicable to sockethub v1+ because the platforms have been moved to their own repositories.

**Comment by skddc** [comment]
Ah, makes sense.
