### ISSUE TITLE
Re-add XMPP platform

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#197]
We're planning to dogfood Kosmos for private company chats within the next 4 weeks, and we'd like to use XMPP instead of IRC from the beginning.

I'm actually not sure it makes sense to depend on Sockethub for that, or if it's better to use BOSH directly from Hyperchannel. That way we (and everyone else) could run the private server scenario without even needing Sockethub. On the other hand, we'd have to have a different implementation for that backend, of course.

**Comment by skddc** [comment]
The Hubot XMPP adapter has commented code for all we need afaics:

https://github.com/markstory/hubot-xmpp/blob/master/src/xmpp.coffee

**Comment by skddc** [comment]
http://otalk.org/ and especially https://github.com/legastero/stanza.io look very promising, too. Someone even built a whole chat app on top of XMPP: https://getkaiwa.com/

**Comment by skddc** [comment]
So, after the last discussions we had, I think we agreed on using Sockethub, because being able to use the same ActivityStreams API for different protocols is kind of the whole idea.

**Comment by skddc** [comment]
Another option: http://strophe.im/

**Comment by silverbucket** [comment]
@skddc strophe is all BOSH client-based though. Not something useful for Sockethub

**Comment by silverbucket** [comment]
@skddc actually most of these projects seem to be based on BOSH

**Comment by silverbucket** [comment]
@skddc the only node-based library I see in all these projects is with hubot-xmpp, which uses node-xmmp-client, of which node-simple-xmpp is a wrapper for. So we may still need to be using the same setup. Which will make the port more straightforward at least. But looks like the ecosystem hasn't really grown much over the past few years.

**Comment by skddc** [comment]
https://github.com/legastero/stanza.io looks node-based to me. And WebSocket clients are certainly available for node.js too.

**Comment by silverbucket** [comment]
@skddc ah cool, overlooked that. For some reason I remember that name and that we looked at it, but can't remember anything more. So I'll give it another shot when I next have a chance

**Comment by silverbucket** [comment]
Sorry for the late update. The XMPP platform has been re-ported to the new version of sockethub and exists at https://github.com/sockethub/sockethub-platform-xmpp

**Comment by skddc** [comment]
![fuck-yeah-funk](https://cloud.githubusercontent.com/assets/842/21952706/9b9aeca2-da5e-11e6-825e-9aa9f822a847.gif)
