### ISSUE TITLE
Example config for nginx & haproxy

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#200]
I'm having trouble to get Sockethub working correctly behind nginx. Would be nice to have an example config for people trying to do the same.

**Comment by silverbucket** [comment]
OK, so in summary the issues were that socket.io had issues with:
* Multiple values for the CORS headers
* LTE here in Indonesia wasn't liking WebSockets (VPN fixed the issue).

@skddc if you have a working nginx example, maybe we could add it to the github Wiki or something.

**Comment by skddc** [comment]
Yes, I'll add something to the wiki. Maybe also add your HAproxy config. Then we just need someone to add an Apache example to have all the popular cases covered I guess.

**Comment by skddc** [comment]
How about adding a label for documentation issues? I think there's a lot to do there...

**Comment by silverbucket** [comment]
Good call, added documentation label. Will get a haproxy example ready in the next few days.

**Comment by skddc** [comment]
I added the nginx example: https://github.com/sockethub/sockethub/wiki/Using-nginx-as-reverse-proxy-for-Sockethub

@silverbucket Care to add your haproxy one?

**Comment by silverbucket** [comment]
@skddc done!

**Comment by silverbucket** [comment]
put them on a shared `server configuration examples` page:
https://github.com/sockethub/sockethub/wiki/Server-Configuration-Examples

**Comment by skddc** [comment]
![check](https://cloud.githubusercontent.com/assets/842/24154453/2b5e11f2-0e49-11e7-8ba9-0441994f0a73.gif)
