### ISSUE TITLE
"feeds" example doesn't work

### ISSUE THREAD

**Issue by abliss** [sockethub/sockethub#203]
Looks like you need to update sockethub-platform-feeds from 0.0.1 to 0.0.2 (which it seems was never published on https://www.npmjs.com/package/sockethub-platform-feeds ).

(workaround: just changing `job.target.id` to `job.target["@id"]` at `index.js` line 233 was enough to get it to work for me.)

**Comment by silverbucket** [comment]
pushed a new version, should work now. switched to semver 1.x and now at 1.0.1
