### ISSUE TITLE
activity-streams should provide sourcemaps

### ISSUE THREAD

**Issue by gregkare** [sockethub/sockethub#237]
See https://github.com/67P/hyperchannel/issues/161

<strike>We are using https://sockethub.kosmos.org:10550/activity-streams.js, but now only https://sockethub.kosmos.org:10550/activity-streams.min.js is provided</strike>

We're changing Hyperchannel to use the minified version, having sourcemaps would help when developing

**Comment by gregkare** [comment]
#238 did not fix the issue, as the activity-streams npm module doesn't contain the unminified file since [3.1.0](https://github.com/silverbucket/activity-streams.js/tree/v3.1.0/browser). Sockethub depends on 4.1.0 right now

**Comment by silverbucket** [comment]
@galfert @gregkare - this should no longer be an issue, as activity-streams.js is packaged/bundled together into the sockethub-client.js

**Comment by silverbucket** [comment]
Turns out we do still need sourcemaps for activity-streams.js
