### ISSUE TITLE
[platform idea] Open Graph (fetch metadata)

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#244]
https://ogp.me

I think this would be useful in unhosted apps both for convenience (i.e. not having to parse random web pages, or use an additional lib to do so), as well as to get around Single Origin restrictions (no CORS headers on target URL response).

**Comment by silverbucket** [comment]
@raucao does this issue duplicate the recent one you created #557 ?

**Comment by raucao** [comment]
Ah yes, 100%.
