### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#252]
Just seeing these on a fresh install of `sockethub@3.1.3-alpha.13` just now, so I thought it wouldn't hurt to document here:

* @types/typescript@2.0.0: This is a stub types definition for TypeScript (https://github.com/Microsoft/TypeScript). TypeScript provides its own type definitions, so you don't need @types/typescript installed!
* core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
* node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
* node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
* node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js

**Comment by silverbucket** [comment]
Thanks for making note of these. The typescript types have been removed.

The core-js warnings are due to the `kue` package which is deprecated and I plan to migrate to `bull` eventually: https://github.com/sockethub/sockethub/issues/239

The xmpp deprecation is known, it's not going to be a simple switch but there's an issue for it here: https://github.com/sockethub/sockethub-platform-xmpp/issues/21

**Comment by skddc** [comment]
> The xmpp deprecation is known, it's not going to be a simple switch but there's an issue for it here: [sockethub/sockethub-platform-xmpp#21](https://github.com/sockethub/sockethub-platform-xmpp/issues/21)

The author of those libs is attending https://wiki.xmpp.org/web/Sprints/2020_March_Berlin which I proposed to also do within the first 2020 Kosmos Hackdays:

https://gitea.kosmos.org/kosmos/meta/issues/12

**Comment by silverbucket** [comment]
Yeah, we talked about it on the last call with @galfert and @gregkare - I wrote it in my calendar just in case, but I probably won't be able to make it. I will be in Berlin during mid-April though to play a show at attend Superbooth, but would also be into a day or two of hacking with you all :)

The XMPP lib switch should be straight forward as the docs and API seem good, but it will just require a lot of rewriting and testing.

**Comment by skddc** [comment]
Would be nice if you could actually add that as a comment to the planning issue, because otherwise nobody else can see it. Personally, I won't be back in Berlin after that, because we're building out the interior of Hacker House then.

**Comment by silverbucket** [comment]
Also having a `yarn` issue with `jsdoc2md` (https://github.com/jsdoc2md/jsdoc-to-markdown/issues/206) when I did an `npm install` and `yarn install`, grabbing all packages in node_modules with versions, I got 8 differences. Some where missing entirely while others were major versions off. Weird.
