### ISSUE TITLE
Dependencies missing when running sockethub as dependency

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#255]
@galfert added the latest release to Hyperchannel to lock the version and be able to run Sockethub from the Hyperchannel repo. But it looks like not all dependencies are being installed:

```
Error: ENOENT: no such file or directory, stat '/home/basti/src/kosmos/hyperchannel/node_modules/sockethub/node_modules/socket.io-client/dist/socket.io.js'
Error: ENOENT: no such file or directory, stat '/home/basti/src/kosmos/hyperchannel/node_modules/sockethub/node_modules/activity-streams/browser/activity-streams.min.js'
```

**Comment by silverbucket** [comment]
This is during an include from the browser client trying to include `activity-streams.js` from the sockethub service. Sockethub is likely unable to pathfind it's way to the browser as file, so either improve the path finding or see if package.json has a special directive for referencing browser include files.

**Comment by silverbucket** [comment]
https://github.com/defunctzombie/package-browser-field-spec#spec

**Comment by galfert** [comment]
I tried again with the [latest master](https://github.com/sockethub/sockethub/tree/893e033992186fbf37551849caa3863a5740b53b). The libraries can now be loaded without errors when starting Sockethub from the Hyperchannel repo.

But I got another error when trying to connect:

```
Error: Cannot find module '/Users/galfert/code/active/kosmos/hyperchannel/dist/platform.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I think I already found a fix for this. PR incoming...
