### ISSUE TITLE
Switch away from using domains

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#257]
During a pairing session with @skddc - we discovered problems using the new rewritten https://github.com/xmppjs/xmpp.js from within domains (which are currently being used to "sandbox" a platform instance within sockethub).

After giving it some thought and refreshing my memory on the topic, while Domains are deprecated, they are still supported and won't be removed until a replacement for their functionality is implemented. Currently it looks like all alternative designs have been removed from review. So it's in a bit of a limbo state at the moment.

It seems like switching to separate child processes for each worker is probably the safest way to go right now. I've been playing around with it but haven't found an ideal balance yet. Problem areas:

1. passing secrets - the main thread and worker threads will need to share some secrets in order to encrypt and decrypt messages on the redis queue. 
* This could be done with passing the secrets into the process via. stdin (not via parameter) so that the secrets are invisible to the system process list. Not sure if this exposes the secrets via some other vector though, but I don't think so.

2. we'll need a reliable way to spawn a worker for every unique instance of a persistent platform and share access to that instance when the user proves they have access to it.
* The main thread could both handle incoming messages/jobs from clients, put them on the queue, additionally pop them off the queue but spawn a thread to handle the job. This could be kind of slow but would only need to be done for:
- persistent platfoms
- that have not yet been initialized (so on the initial connect, things might be slower).
3. safe handling of any kind of unexpected errors to destroy the thread and make sure new ones are created as needed with no weird states or zombie processes.

**Comment by skddc** [comment]
How about we postpone solving this for now, and remove the isolation entirely (maybe only in development env)? That way, we can migrate XMPP and have it working asap, and then we can make the code production-ready after that. What do you think?
