### ISSUE TITLE
Remove passing of credentials on each platform method

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#287]
Only pass in credentials on `connect`

**Comment by galfert** [comment]
Shouldn't this issue still be kept open? So far #344 was only in preparation of removing it from the other methods.

**Comment by silverbucket** [comment]
@galfert I don't think so, since now whether credentials are passed in or not is left as a config option to the platform, the platforms can be reworked over time with their own issues (eg. just refactoring those platforms in general).
