### ISSUE TITLE
EMAIL: pop3 support

### ISSUE THREAD

**Issue by michielbdejong** [sockethub/sockethub#32]
i'm gonna go with https://github.com/ditesh/node-poplib for POP3. i can't think of a good ActivityStreams verb, so i'll just go with 'retrieve' for now. i think all platforms can deliver activities they retrieve to the 'inbox' module on remoteStorage, if the sockethub server has access to that.

we can switch this sort of things around as we see how it looks, obviously, but i want to have something working for my blogpost tomorrow.

**Comment by silverbucket** [comment]
moved to https://github.com/sockethub/sockethub-platform-email/issues/1
