### ISSUE TITLE
add pgp support

### ISSUE THREAD

**Issue by michielbdejong** [sockethub/sockethub#44]
i'm using sockethub to send out pgp-signed email, here is my code:

```
https://github.com/sockethub/sockethub/pull/40/files#L1R22
```

sorry that i didn't have time to do the whole pull-request thing with the tests and the schemas and the docs and everything, i have lots of other stuff piling up this week, but i wanted to at least share my code with you, you're free to use it however works best.

hopefully it will at least serve as example code for how pgp signing can work. this is the code i use in production for actual real email sending. :)

fwiw i plan to spend some time helping with actual sockethub development in May, until then i'll just be your user base and send you support tickets! :)

**Comment by michielbdejong** [comment]
Issue more than a year old, closing.

**Comment by skddc** [comment]
So, btw, there's a new discovery option for PGP certs, using a .well-known resource on the email domain instead of key servers. Might make sense to add discovery for that to Sockethub? Could obviously be used for any user address, incl. RS and XMPP for example.
