### ISSUE TITLE
Sockethub Ejabberd Compatibility

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [sockethub/sockethub#472]
Is Sockethub Compatible With Ejabberd Server?
If that is done, this project will receive significant further momentum.
Ejabberd is one of the most used xmpp servers.
Connection could be over websockets, https(?) and preferably not over BOSH
Particularly support for React Native (with Expo) and ReactJS clients is missing in this area on client side.

**Comment by silverbucket** [comment]
Hi @mayank-mundhra-2012 Sockethub is currently being used against ejabberd servers quite a lot. That said there are a still several XEPs that are still not fully support (though we are continually working toward supporting as many as we can). As it stands now, requesting/adding/removing contacts, getting contact lists, joining rooms, presence updates etc. are all supported. 

Sockethub listens via WebSockets and proxies data to/from the client and ejabberd service. We intentionally leave client implementation up to the app developer, though there is a `sockethub-client.js` which can be included to assist in easily sending and receiving messages to/from the Sockethub service.

**Comment by mayank-mundhra-2012** [comment]
Thanks @silverbucket. Is there a place listing XEPs supported. Can remaining XEPs be supported?
I couldn't find sockethub-client.js in a cursory search. Could you point out where it is?
Is there a client library that works and provides support for React Native (with Expo) and React JS with ejabberd server. If you'll could make something like that, a lot of people would benefit. A lot of people use React Native + Expo or ReactJS for client side. If there is support for websocket, push notification and all other XEPs it will be great.

**Comment by silverbucket** [comment]
Hi @mayank-mundhra-2012 There's not a list of supported XEPs, though that's a good suggestion. You can see the actions that are currently implemented listed in the `sockethub-platform-xmpp` package: https://github.com/sockethub/sockethub/tree/master/packages/sockethub-platform-xmpp

The sockethub-client.js is served from the sockethub service (eg. `localhost:10550/sockethub-client.js`) and the source can be found here https://github.com/sockethub/sockethub/blob/master/packages/sockethub/src/js/client.js

As for React, Expo, etc. we have no plans to write any tooling for these frameworks at the moment, as it's out of the scope for this project. That said if someone were to write components we'd be happy to link to them and possibly help support them in the future. We just don't have the capacity to develop and maintain our own set of libraries for every popular front-end framework.

**Comment by mayank-mundhra-2012** [comment]
I understand about tooling. I meant 3 different things in different contexts
1. Tooling
2. Mobile and web compatible library. Does not matter whether React Native or Swift or Android. What is important is features that support them.
3. Client side library - javascript, java, etc (I came across JSXC, Xmpp.js, stanza.js,etc).

**Comment by raucao** [comment]
The client-side library is the aforementioned `sockethub-client.js`. Everything else is out of scope for the core project, but can be created by anyone who wishes to do so.
