### ISSUE TITLE
Connect error AS object should contain actor/target

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#492]
E.g. a "not-authorized" comes back without knowing which account failed to authorize.

**Comment by silverbucket** [comment]
@raucao -- can you be specific on which event handler you're receiving the error object? And also are you sure there's not a more complete object in the `failure` event? For example, when I try to log in with invalid credentials:

```
{
  @type: "connect"
  actor: {
    @id: "jimmy@kosmos.org/SockethubExample"
    @type: "person"
    displayName: "jimmy"
    image: {url: "http://example.org/image.jpg", mediaType: "image/jpeg", width: 250, height: 250}
    url: "http://sockethub.org"
  }
  context: "xmpp"
  object: {
    @type: "error"
    content: "SASLError: not-authorized - Invalid username or password"
  }
}
```

Now, there's also another more generic error message which comes back on the `completed` event:
```
{ 
  @type: "error"
  context: "xmpp"
  object: {
    @type: "error"
    condition: "not-authorized"
    content: "Invalid username or password"
  }
}
```
However the first case should provide all the info you need. Are you not seeing it?

**Comment by raucao** [comment]
Yes, I didn't get a failure. Apparently it was superceded by this failure:

![Screenshot from 2021-08-29 16-25-27](https://user-images.githubusercontent.com/842/131253891-fcc96280-21c6-4cd3-bc24-fbd3d556507b.png)

I just tried with master, where that particular one has been resolved. However, now it's actually even worse. Instead of the connect error message with the wrong-credentials message, there is now only another `message` with another validation error, and no `failure` event at all. And there's also a second error message about something that shouldn't be public API:

![Screenshot from 2021-08-29 16-29-45](https://user-images.githubusercontent.com/842/131253955-39922cfd-b6be-4886-a80c-c16f29cd8819.png)

**Comment by silverbucket** [comment]
@raucao Weird - I'm unable to recreate this behavior. When I enter invalid credentials I just get back an error as I showed in my last message. Can you tell me the steps and perhaps include the entire console log along with the above output?

**Comment by raucao** [comment]
You can just try it in Hyperchannel. I did not change any Hyperchannel code, but only updated the Sockethub master branch.

**Comment by silverbucket** [comment]
@raucao using both master branches of Sockethub and Hyperchannel. I get to the "add an account page" (looks nice btw!) and enter jimmy but make a bad password. I get the expected error object (without actor or target info), however I don't have any way of knowing if there's a listener on the failure event. 

I don't see the other issues you sent screenshots of, you say this is happening for you every time?

**Comment by raucao** [comment]
Hmm, no idea what state Sockethub got into at that time then. Now it works, even though I changed nothing about either Hyperchannel or Sockethub masters since I wrote that comment.  ¯\_(ツ)_/¯

The validation failure event is now gone. However, there is no other failure event as you also saw. (All events are logged as debug messages to the console, with a prefix for "SH failure", "SH message" etc.)

There is a warning logged from `activity-streams-min.js`, which looks like the culprit:

    invalid property: "condition"
    
Unfortunately, we don't have a source map for that, so it's not possible to see the original source code there.

**Comment by raucao** [comment]
Just FYI, because my current IP requires SASL and thus I have a failing IRC connect as demo: it also only sends a "message", but not a "failure". However, the IRC one does contain a target to identify the account:

![Screenshot from 2021-08-30 15-56-09](https://user-images.githubusercontent.com/842/131350835-24ea7cbe-1691-45e6-9fb5-17692aebca35.png)

**Comment by silverbucket** [comment]
> ```
> invalid property: "condition"
> ```
> Unfortunately, we don't have a source map for that, so it's not possible to see the original source code there.

This is definitely not the issue, it's simply a warning of an unknown property of an AS object (the error object contains that property and we assign it to the `object` property as-is), doesn't obscure or abort any operation.



> Just FYI, because Libera requires SASL for my current IP, and thus I have a failing IRC connect as demo: it also only sends a "message", but not a "failure". However, the IRC one does contain a target to identify the account:

I've verified that, using Hyperchannel, Sockethub does send a message on the `failure` channel, so I'm guessing Hyperchannel is not attached to `failure` events at that time.

Just for posterity, I've added a small addition which will ensure an actor exists (if we have that info and the AS object doesn't already have an actor property) so that even random errors coming up as messages will have an actor property if one is available. PR forthcoming.

**Comment by raucao** [comment]
> I've verified that, using Hyperchannel, Sockethub does send a message on the `failure` channel, so I'm guessing Hyperchannel is not attached to `failure` events at that time.

As stated, and also shown before (when the failure was logged with the same code), Hyperchannel logs *all* Sockethub events to the debug console, including `failure`s:

https://github.com/67P/hyperchannel/blob/13db2a53e6d7329aead45c4b5618ae13ad24a8f8/app/services/coms.js#L74

https://github.com/67P/hyperchannel/blob/master/app/services/coms.js#L489-L491

https://github.com/67P/hyperchannel/blob/13db2a53e6d7329aead45c4b5618ae13ad24a8f8/app/services/logger.js#L35
