### ISSUE TITLE
Additional "completed" messages/events emitted when successfully connecting after failed connects

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#494]
The connect situation is still a bit buggy overall:

1. When supplying wrong credentials for an account, and then giving the correct credentials, the previous failed connect attempts seem to all be fired again and succeed as well, resulting in additional "completed" messages to the client.
2. After supplying invalid credentials once, the next connect attempt after supplying correct credentials fails, and then only the following one actually succeeds. I wasn't able to find out why (from the client POV).

**Comment by silverbucket** [comment]
@raucao I am unable to reproduce this, can you try on the simple XMPP example bundled with Sockethub? This would remove any possible issues with Hyperchannel. I tried connecting with invalid credentials, then with valid ones, I received only the expected single completed job event.

**Comment by raucao** [comment]
Ah, this must be due to not being able to unregister handlers then! Sorry.

**Comment by silverbucket** [comment]
Yeah, there seem to be a lot of issues coming up due to the client wrapper, making #526 higher priority. I'll start working on it after this next release is made.

**Comment by raucao** [comment]
Btw, already solved in Hyperchannel by using `.onAny` and `.offAny`, which may be responsible for it not joining channels directly after adding an account and connecting.
