### ISSUE TITLE
sockethub-client overwriting `socket.on` with a version that doesn't support multiple listeners

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#495]
Exactly as stated in the title, it's not possible to register multiple listeners to the same event name with the current `sockethub-client`. It seems to want to do some additional ActivityStreams parsing, but in my use case there was actually no difference between the emitted parsed events and what I got when circumventing the issue by using the `socket.onAny` API for the additional listener instead.

**Comment by silverbucket** [comment]
You are correct that there is some middleware which parses the ActivityStreams, its main purpose is to ensure certain properties exist, expand and collapse objects. For example:

You can register an object once:
```js
sc.ActivityStreams.Object.create({
  '@id': 'foo@kosmos.org`,
  '@type': "person",
  displayName: "Mr.Foo"
});
```

And any time it's sent or received with the ID string:
```js
{
 actor: 'foo@kosmos.org',
 ...
}
```

It would automatically be expanded:
```js
{
  actor: {
    ''@id': 'foo@kosmos.org`,
    '@type': "person",
    displayName: "Mr.Foo"
  }
}
```
Additionally, there is replay functionality in the sockethub client, so it can replay unconfirmed commands when needed (this greatly improved the reliability of keeping state of rooms joined, messages sent, etc.). 

But yeah, I didn't make the new handlers flexible enough, looks like there's just one handler for each unit event name: https://github.com/sockethub/sockethub/blob/8200286125bea0638bbc87c4168cadc1ac4c2eeb/packages/sockethub/src/js/client.js#L148-L158

Should be a fairly simple fix, will try to get to this soon.
