### ISSUE TITLE
Rewrite sockethub-client to use EventEmitter as a proxy for events

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#526]
The user will be exposed to sockethub-clients EventEmitter, which will pass along to/from any event activity to socket.io's EventEmitter so that it's able to perform any needed actions while still exposing a feature-complete EventEmitter API.

**Comment by raucao** [comment]
Just for context for others: it is currently not possible to deregister event handlers/listeners, and refactoring the whole event handling as described is a much better and cleaner fix than hacking more custom code around it.
