### ISSUE TITLE
Decouple connect and join steps in IRC platform 

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#529]
I'm not sure if this is new, or how it was before, because Hyperchannel just sends channel joins without even caring about the server being connected first. But now that I'm implementing it properly, I'm seeing that there's just no event being emitted at all when sending credentials from the client to Sockethub.

The Sockethub logs also don't mention any server connection attempts:

```plain
  sockethub:core:wnJuJ9Ivg9qrjCn1AAAB socket.io connection +0ms
  sockethub:validate:wnJuJ9Ivg9qrjCn1AAAB applying schema validation for activity-object +0ms
  sockethub:validate:wnJuJ9Ivg9qrjCn1AAAB applying schema validation for credentials +0ms
  sockethub:core:wnJuJ9Ivg9qrjCn1AAAB credentials encrypted and saved +3s
```

**Comment by silverbucket** [comment]
This was actually something that you wanted to correct when we were working on the XMPP platform. Previously joins would auto connect. Now the connect needs to be explicit and the platforms don’t auto connect anymore.

Cheers,
Nick

**Comment by raucao** [comment]
Cool. But there is no documented way of connecting to an IRC server in the IRC platform.

**Comment by raucao** [comment]
Had a look at the source just now, and I think I misunderstand what you meant. AFAICS it works like that in XMPP now, but in IRC you still need to join in order to connect.

**Comment by silverbucket** [comment]
@raucao -- re-reading the initial description, I think I misunderstood when I responded above. You're saying that saving credentials doesn't result in any confirmation that the credentials were saved, right? -- if so the title is misleading or if not, the description is. Can you clarify?

**Comment by raucao** [comment]
> You're saying that saving credentials doesn't result in any confirmation that the credentials were saved, right?

Yes. But the misunderstanding was that sending the credentials would issue a connect, which it turned out it does not. So the whole issue is invalid I think. But we still need to implement the actual `connect` change for the IRC platform, so it is consistent with XMPP, and so that we can also know if a connection works before joining channels.
