### ISSUE TITLE
Investigate scaling/re-using Redis connections for Bull

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#563]
This implementation was used however as @Cobertos noticed, wasn't operating correctly with custom Redis config. More time will need to go into investigating this implementation, and making sure we're managing the Redis connections properly, with tests and verification of connections used/cleaned up.

- https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections
- https://github.com/OptimalBits/bull/issues/2081
- https://github.com/OptimalBits/bull/issues/1798

Not high on the priority list, unless we start running into Redis connection issues.

**Comment by raucao** [comment]
> Not high on the priority list, unless we start running into Redis connection issues.

I agree. I'd even say it's "low", not "medium".

**Comment by silverbucket** [comment]
This is no longer applicable as we switched to `bullmq` the rewrite of `bull`
