### ISSUE TITLE
Notify user when event names are incorrect

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#570]
As @raucao points out:

> OK, so now I found out why Hyperchannel isn't logging the failure messages for the connect. Instead of the normal "failure" event name, which other failures do use, this one uses the event name "failed".

> I think we need to manually ensure that these are all consistent for now. But in the future, trying to send unknown event names should probably cause at least a console warning, or ideally a linting error.

**Comment by raucao** [comment]
More important than notifying the user is that event names are consistent and correct to begin with. Right now, the connect error event is not the same as the other failure events we get in Hyperchannel, which are "failure" events. I just had a look into this, and now I'm actually more confused than before.

[The documentation says](https://github.com/sockethub/sockethub/wiki/Sockethub-Client#events) the event name is `failure`, which [seems to be implemented in a global utility function as well](https://github.com/sockethub/sockethub/blob/be00ce47b7c2efcbeffcbb8ef5af6c3e8e1dc348/packages/sockethub/src/sockethub.ts#L67). Hence, we always got `failure` messages for a few things in Hyperchannel.

However, the client has some implementation for `failed` events and does not mention `failure` specifically at all (but it does mention `message` and `completed`).

So now I'm wondering if `failed` is somehow different in intent than `failure`. Perhaps one for socket failures and the other one for platform failures?

**Comment by silverbucket** [comment]
This should also be fixed in the sockethub-client PR, which extends EventEmitter (docs still need to be updated though)
