### ISSUE TITLE
Schema validation fails for room attendance message

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub#638]
When using the latest SH master, I see an error message in the logs:

> sockethub:core:PxH7yFFU2_XXX10bAAAD failure handling message. Error: actvity-stream schema validation failed: must be equal to one of the allowed values

This happens when trying to request the room attendance list with the following message:

```json
{
    "type": "observe",
    "context": "xmpp",
    "actor": {
        "id": "galfert@kosmos.org/hyperchannel",
        "name": "galfert",
        "type": "person"
    },
    "target": {
        "id": "kosmos-random@kosmos.chat",
        "name": "kosmos-random@kosmos.chat",
        "type": "room"
    },
    "object": {
        "type": "attendance"
    }
}
```

**Comment by galfert** [comment]
You can use the Hyperchannel version in https://github.com/67P/hyperchannel/pull/259 to try it yourself.

**Comment by silverbucket** [comment]
@galfert I checked out that kosmos branch, and ran it against the master branch of the sockethub repo. When I log in with the jimmy test account, I get the following error:
```
  sockethub:validate:q3DRlt0y_sWBTYkwAAAB applying schema validation for activity-object +0ms
  sockethub:middleware:credentials Error: activity stream must contain a type property.
  sockethub:middleware:credentials     at Array.expandActivityStream (/Users/njenning/code/projects/sockethub/packages/sockethub/dist/middleware/expand-activity-stream.js:20:14)
  sockethub:middleware:credentials     at next (/Users/njenning/code/projects/sockethub/packages/sockethub/dist/middleware.js:47:43)
  sockethub:middleware:credentials     at Socket.<anonymous> (/Users/njenning/code/projects/sockethub/packages/sockethub/dist/middleware.js:53:13)
  sockethub:middleware:credentials     at Socket.emit (node:events:394:28)
  sockethub:middleware:credentials     at Socket.emitUntyped (/Users/njenning/code/projects/sockethub/packages/sockethub/node_modules/socket.io/dist/typed-events.js:69:22)
  sockethub:middleware:credentials     at /Users/njenning/code/projects/sockethub/packages/sockethub/node_modules/socket.io/dist/socket.js:428:39
  sockethub:middleware:credentials     at processTicksAndRejections (node:internal/process/task_queues:78:11) +0ms
```

Is there an easy way to switch on the ability to view the AS objects being sent and receive in the Hyperchannel JS console?

**Comment by galfert** [comment]
That's strange. I don't get that error.

When connecting IRC, it should already show you the AS object (see https://github.com/67P/hyperchannel/blob/5e4932ce501a1c010edd4e8f5f6b485f99f13b08/app/services/sockethub-irc.js#L77)

For XMPP you'll need to add the `credentialsJob` to the log statement here: https://github.com/67P/hyperchannel/blob/5e4932ce501a1c010edd4e8f5f6b485f99f13b08/app/services/sockethub-xmpp.js#L77

**Comment by silverbucket** [comment]
The credentials object needs to have a type base property:
```js
const credentialsJob = {
      actor: userAddress,
      context: 'xmpp',
+    type: 'credentials',
      object: {
        type: 'credentials',
        username: userAddress,
        password: password,
        resource: 'hyperchannel'
      }
    };
```

**Comment by silverbucket** [comment]
@galfert But now that I no longer get the credential error, when I click "Continue"... the app doesn't progress to log in. It just stays on the login screen, even though the connect job was successful.

**Comment by galfert** [comment]
That's all strange. I'm getting different behaviour than you. Maybe we should pair on it? Let me know when you have some time. I don't think it should take very long.

**Comment by silverbucket** [comment]
@galfert sure I'll ping you on XMPP in an hour or two

**Comment by silverbucket** [comment]
I've created https://github.com/sockethub/sockethub/issues/639 to track additional schemas definitions for the platform object types that aren't yet covered. We can use this ticket to track the improvement of that useless error message.
