### ISSUE TITLE
Add schema definitions for platform objects types

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#639]
Certain object types that are used in the irc and xmpp platforms were overlooked, and when the schema validation improved (became more strict & reliable) those types were then invalidated before reaching the platform. 

These are:

* attendance
* presence
* topic
* address

**Comment by raucao** [comment]
From dev chat:

```
<raucao> regarding the object type "attendance", we also need "info" or "room-info" [...]
<raucao> btw, if "observe" is only from IRC, i think we should change the AS object to be "query" instead
<raucao> while we're changing it anyway
<raucao> good moment for breaking changes
<raucao> wdyt?
```

**Comment by silverbucket** [comment]
@raucao This isn't really the ticket to piggy back new definitions, it's for defining what's already being used. Could you create tickets and or PRs with an explanation for what it would be used for?

> btw, if "observe" is only from IRC, i think we should change the AS object to be "query" instead

What makes you say observe is only for IRC? It should be for any platform that wants to use it. Changing it to query could make sense though, but again, these should be separate tickets. It deserves more careful consideration and hopefully we can correlate this to AS type definitions (which easier said than done, for sure, and maybe not possible).

**Comment by raucao** [comment]
I think this is actually the perfect issue to tackle both questions within. The first one is about the already missing attendance type, and the second question is about using these breaking changes to piggyback more useful breaking changes on top.

The question about observe is if it was named this way intentionally outside of IRC terminology, or if it's only named this way due to the IRC term. If the latter is the case, then I'm proposing to change it to "query" instead, because the term 1) makes more sense in the language itself and 2) is better suited for many more query types.

**Comment by silverbucket** [comment]
> I think this is actually the perfect issue to tackle both questions within.

This ticket is to fix a bug that was introduced when stricter schema checks were implemented. It's not for addressing any new questions that you're bringing up. Please create separate tickets.

To answer your question, `observe` is not intentionally outside IRC terminology, nor is it only named that way due to it. It was the verb chosen at the time (~2013) for lack of a better idea to describe a user viewing (and by that vein, as applies to sockethub, requesting) a piece of data. https://groups.google.com/g/activity-streams/c/Egjz-3hkZvU?pli=1

**Comment by raucao** [comment]
Again, I disagree. If the attendance object type is broken right now, it is based on "observe", and the issue title is "Add schema definitions for platform objects types", then the only issue that makes sense to add this for me is this one.

Please create issues the way you think makes sense otherwise, because I don't know how you think it makes sense. Thank you!

**Comment by silverbucket** [comment]
You are conflating schema with platform functionality. Nothing in the platform was broken, the JSON object validation process in core was missing validation for some methods of the platforms. That is a bug that was introduced a few months ago. (eg. We could still receive from these platform methods, but Sockethub core was failing to route request objects from the user to the the platform method). I simply fixed that bug.

The description explains these were for existing types, no types were added or changes, nothing new was added to anything but the validation+schema process. 

I don't know why you want me to create the tickets for you, I have no special criteria other than they don't belong in this ticket, and why you wont just create them? I have very little to go on based on your pasted in chat comments. It's clear you have some ideas for changes to the vocabulary, and I'm open to those ideas, but they should be discussed in a ticket where you can explain why you think those changes should be made (I have no context).

**Comment by galfert** [comment]
I also think this ticket should just be for fixing any of the types that used to work before.

As for the new type, why not just use the issue for the actual feature that will require that new type, ie. #540?

**Comment by raucao** [comment]
> You are conflating schema with platform functionality.

I am not. Without the type being valid, I cannot implement the functionality. My request was purely about validation, not about implementing anything feature-wise.

**Comment by raucao** [comment]
New issue is for observe->query is #647.
