### ISSUE TITLE
AS2.0 names not working for IRC platform

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub#646]
The name changes introduced #574 don't seem to work for the IRC platform yet.

E.g. I received the following message, which still contains `@type`, `@id` and `displayName`.

```json
{
    "actor": {
        "@type": "person",
        "@id": "wubbalubbadubdub@irc.libera.chat",
        "displayName": "wubbalubbadubdub"
    },
    "target": {
        "@type": "room",
        "@id": "irc.libera.chat/#kosmos",
        "displayName": "#kosmos"
    },
    "object": {
        "role": "member",
        "type": "presence"
    },
    "published": "1639411352558",
    "context": "irc",
    "type": "update"
}
```

**Comment by silverbucket** [comment]
@galfert Hmm, this is really odd, because there is no instance of `@id` in the IRC platform code. 

Are you using an `npm` installed `sockethub-platform-irc` module or did you run `yarn install` from the sockethub root (which uses bootstrap to link local packages together)?

**Comment by galfert** [comment]
I ran `yarn install` and `yarn run build`, just to be sure.

**Comment by galfert** [comment]
You can try https://github.com/67P/hyperchannel/pull/259 to see if it happens for you as well. The Browser console shows the received messages.

**Comment by galfert** [comment]
@silverbucket the `irc2as` package seems to still contain the old names.
