### ISSUE TITLE
Tag and publish pre-release of 5.0

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#694]
@silverbucket Could you tag a `5.0.0-beta.1` (using `npm version prerelease`) and publish it to NPM? You could `dist-tag` it as `@next` on NPM for example, like so: `npm publish --tag next`.

This way we can regularly deploy the betas on `sockethub.kosmos.org` and deploy the latest Hyperchannel versions with those betas as well.

**Comment by silverbucket** [comment]
This should be done now
