### ISSUE TITLE
Do we need to still support Node 14.x ?

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#788]
Sveltekit, which is being used in the new examples module branch, only supports node 16 and above, wondering what version Hyperchannel/the infrastructure needs, if it's 14, might an upgrade be easy enough? cc @raucao @galfert @galfert

**Comment by raucao** [comment]
We're running LTS/16 in production at the moment.

**Comment by silverbucket** [comment]
Resolved in https://github.com/sockethub/sockethub/pull/824
